AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  instance_scheduler

  Sample SAM Template for instance_scheduler

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Tracing: Active
    Runtime: python3.9
  Api:
    TracingEnabled: true

Resources:
##TENER EN CUENTA UTC QUE SON 3 HS MAS QUE EN ARGENTINA
  shutdown:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./src/shutdown
      Handler: app.lambda_handler
      Environment:
        Variables:
          TAG: '20:00'
      Policies:
        - Statement:
          - Sid: EC2ShutDownInstances
            Effect: Allow
            Action:
            - ec2:DescribeInstances
            - ec2:StopInstances
            Resource: '*'
      Events:
        CronEventStop:
          Type: Schedule
          Properties:
            Schedule: cron(0 20 * * ? *)
            Enabled: true
  start:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./src/start
      Handler: app.lambda_handler
      Environment:
        Variables:
          TAG: '06:00'
      Policies:
        - Statement:
          - Sid: EC2StartInstances
            Effect: Allow
            Action:
            - ec2:DescribeInstances
            - ec2:StartInstances
            Resource: '*'
      Events:
        CronEventStart:
          Type: Schedule
          Properties:
            Schedule: cron(0 06 ? * MON-FRI *)
            Enabled: true

